// webui/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  // import Chart from "chart.js/auto";
  import { Canvas, Layer, t, type Render } from "svelte-canvas";
  import type { PlayerCmd, World, XY, XYZ } from "./types";
  import { connectWs } from "./client";

  /**
   * The radius of the robots and ball, in mm
   */
  const ROBOT_RADIUS = 0.14 * 1000;
  /**
   * The radius of the ball, in mm
   */
  const BALL_RADIUS = 0.043 * 1000;

  const PADDING = 20;

  const { sendCommand, worldState } = connectWs();

  let selectedPlayerId: number | null = null;
  onMount(() => {
    let pressedKeys = new Set<string>();
    const keydownHandler = (ev: KeyboardEvent) => {
      pressedKeys.add(ev.key);
    };
    const keyupHandler = (ev: KeyboardEvent) => {
      pressedKeys.delete(ev.key);
    };

    let interval = setInterval(() => {
      if (pressedKeys.size === 0) return;
      const player = $worldState?.own_players.find(
        (player) => player.id === selectedPlayerId
      );
      if (!player) return;

      const cmd: PlayerCmd = {
        id: player.id,
        sx: 0,
        sy: 0,
        w: 0,
        dribble_speed: 0,
        arm: false,
        disarm: false,
        kick: false,
      };

      if (pressedKeys.has("w")) {
        cmd.sx = 1;
      }
      if (pressedKeys.has("s")) {
        cmd.sx = -1;
      }
      if (pressedKeys.has("a")) {
        cmd.sy = 1;
      }
      if (pressedKeys.has("d")) {
        cmd.sy = -1;
      }
      if (pressedKeys.has("q")) {
        cmd.w = 1;
      }
      if (pressedKeys.has("e")) {
        cmd.w = -1;
      }
      if (cmd.sx !== 0 || cmd.sy !== 0 || cmd.w !== 0) {
        fetch("/api/command", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(cmd),
        });
      }
    }, 1 / 10);

    window.addEventListener("keydown", keydownHandler);
    window.addEventListener("keyup", keyupHandler);
    return () => {
      clearInterval(interval);
      window.removeEventListener("keydown", keydownHandler);
      window.removeEventListener("keyup", keyupHandler);
    };
  });

  let firstTs: number | null = null;
  let render: Render;
  $: render = ({ context: ctx, width: canvasWidth, height: canvasHeight }) => {
    if (!$worldState) return;

    // Add some padding to the canvas
    const width = canvasWidth - PADDING * 2;
    const height = canvasHeight - PADDING * 2;

    const { own_players, opp_players, ball } = $worldState;
    const fieldH = $worldState.field_geom?.field_width ?? 0;
    const fieldW = $worldState.field_geom?.field_length ?? 0;

    /**
     * Convert from server length to canvas length.
     */
    const convertLength = (length: number): number => {
      return Math.ceil(length * (width / fieldW));
    };

    /**
     * Convert from server coordinates to canvas coordinates.
     *
     * The server's coordinate system has its origin at the center of the field,
     */
    const convertCoords = (coords: XY | XYZ): XY => {
      const [x, y] = coords;

      return [
        (x + fieldW / 2) * (width / fieldW) + PADDING,
        (-y + fieldH / 2) * (height / fieldH) + PADDING,
      ];
    };

    // Draw field
    ctx.fillStyle = "#00aa00";
    ctx.clearRect(0, 0, canvasWidth, canvasHeight);
    ctx.fillRect(0, 0, canvasWidth, canvasHeight);

    // Draw field lines
    $worldState.field_geom?.line_segments?.forEach?.(({ p1, p2 }) => {
      const [x1, y1] = convertCoords(p1);
      const [x2, y2] = convertCoords(p2);
      ctx.strokeStyle = "white";
      ctx.beginPath();
      ctx.moveTo(x1, y1);
      ctx.lineTo(x2, y2);
      ctx.stroke();
    });

    // Draw players
    const drawPlayer = (serverPos: XY, orientation: number, color: string) => {
      const [x, y] = convertCoords(serverPos);
      const robotCanvasRadius = convertLength(ROBOT_RADIUS);
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.arc(x, y, robotCanvasRadius, 0, 2 * Math.PI);
      ctx.fill();

      // Draw arrow for orientation
      const angle = -orientation;
      ctx.save();
      ctx.translate(x, y);
      ctx.rotate(angle);
      ctx.beginPath();
      ctx.moveTo(0, 0);
      ctx.lineTo(robotCanvasRadius, 0);
      ctx.closePath();
      ctx.restore();
      ctx.stroke();
    };
    own_players.forEach(({ raw_position, orientation }) =>
      drawPlayer(raw_position, orientation, "blue")
    );
    opp_players.forEach(({ raw_position, orientation }) =>
      drawPlayer(raw_position, orientation, "yellow")
    );

    // Draw ball
    if (ball) {
      const ballPos = convertCoords(ball.position);
      const ballCanvasRadius = convertLength(BALL_RADIUS);
      ctx.fillStyle = "red";
      ctx.beginPath();
      ctx.arc(ballPos[0], ballPos[1], ballCanvasRadius, 0, 2 * Math.PI);
      ctx.fill();
    }

    if ($worldState?.own_players.length > 0) {
      let selectedPlayer = $worldState.own_players[0];
      if (selectedPlayerId === null) {
        selectedPlayerId = $worldState.own_players[0].id;
      } else {
        const _selectedPlayer = $worldState.own_players.find(
          (player) => player.id === selectedPlayerId
        );
        if (_selectedPlayer) {
          selectedPlayer = _selectedPlayer;
        } else {
          selectedPlayerId = selectedPlayer.id;
        }
      }

      const velocityMagnitude = Math.sqrt(
        selectedPlayer.velocity[0] ** 2 + selectedPlayer.velocity[1] ** 2
      );
      if (firstTs === null) {
        firstTs = selectedPlayer.timestamp;
      }
      const ts = selectedPlayer.timestamp - firstTs;

      // const labels = velocityChart.data.labels!;
      // const data = velocityChart.data.datasets[0].data;
      // if (data.length > 100) {
      //   labels.shift();
      //   data.shift();
      // }
      // labels.push(ts);
      // data.push(velocityMagnitude);
      // velocityChart.update();
    }
    if ($worldState?.own_players.length > 0) {
      let selectedPlayer = $worldState.own_players[0];
      if (selectedPlayerId === null) {
        selectedPlayerId = $worldState.own_players[0].id;
      } else {
        const _selectedPlayer = $worldState.own_players.find(
          (player) => player.id === selectedPlayerId
        );
        if (_selectedPlayer) {
          selectedPlayer = _selectedPlayer;
        } else {
          selectedPlayerId = selectedPlayer.id;
        }
      }

      const velocityMagnitude = Math.sqrt(
        selectedPlayer.velocity[0] ** 2 + selectedPlayer.velocity[1] ** 2
      );
      if (firstTs === null) {
        firstTs = selectedPlayer.timestamp;
      }
      const ts = selectedPlayer.timestamp - firstTs;

      // const labels = velocityChart.data.labels!;
      // const data = velocityChart.data.datasets[0].data;
      // if (data.length > 100) {
      //   labels.shift();
      //   data.shift();
      // }
      // labels.push(ts);
      // data.push(velocityMagnitude);
      // velocityChart.update();
    }
  };
</script>

<main class="cont">
  <div class="sidebar">
    <canvas id="velocityChart" width="400" height="400"></canvas>
  </div>
  <div class="sidebar">
    <canvas id="velocityChart" width="400" height="400"></canvas>
  </div>

  <Canvas width={840} height={600} class="canvas">
    <Layer {render} />
  </Canvas>

  <div class="sidebar"></div>
</main>

<style>
  .cont {
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: #191918;
  }

  .sidebar {
    height: 100%;
    flex: 1;
    background-color: #1c1c1c;
  }

  /* .canvas-container {
    flex: 7;
    display: flex;
    justify-content: center;
    align-items: center;
  } */

  :global(.canvas) {
    width: 50vw !important;
    height: auto !important;
  }
</style>

// webui/src/App.tsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import type { PlayerCmd, World, XY, XYZ } from "./types";
import { useWebSocket } from "./client";

const ROBOT_RADIUS = 0.14 * 1000;
const BALL_RADIUS = 0.043 * 1000;
const PADDING = 20;

const App: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [selectedPlayerId, setSelectedPlayerId] = useState<number | null>(null);
  const worldStateRef = useRef<World | null>(null);
  const [crossX, setCrossX] = useState(0); // State for the X position of the cross
  const [crossY, setCrossY] = useState(0); // State for the Y position of the cross
  const fieldW = worldStateRef.current?.field_geom?.field_width! ?? 0;
  const fieldH = worldStateRef.current?.field_geom?.field_length! ?? 0;

  const onUpdate = useCallback((world: World) => {
    worldStateRef.current = world;
  }, []);
  const { sendCommand } = useWebSocket({ onUpdate });

  // Keyboard input
  useEffect(() => {
    const pressedKeys = new Set<string>();
    const keydownHandler = (ev: KeyboardEvent) => {
      pressedKeys.add(ev.key);
    };
    const keyupHandler = (ev: KeyboardEvent) => {
      pressedKeys.delete(ev.key);
    };

    const cmdInterval = setInterval(() => {
      const worldState = worldStateRef.current;
      if (pressedKeys.size === 0 || !worldState) return;
      const player = worldState.own_players.find(
        (player) => player.id === selectedPlayerId
      );
      if (!player) {
        console.error("Player not found");
        return;
      }

      const cmd = createCmd(player.id, pressedKeys);
      sendCommand({ type: "directPlayerCmd", cmd });
    }, 1 / 10);

    window.addEventListener("keydown", keydownHandler);
    window.addEventListener("keyup", keyupHandler);
    return () => {
      clearInterval(cmdInterval);
      window.removeEventListener("keydown", keydownHandler);
      window.removeEventListener("keyup", keyupHandler);
    };
  }, [selectedPlayerId]);

  // Canvas rendering
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let frame: number | null = null;
    const render = () => {
      const worldState = worldStateRef.current;
      if (!worldState) {
        frame = requestAnimationFrame(render);
        return;
      }

      const { own_players, opp_players, ball } = worldState;
      const width = canvas.width - PADDING * 2;
      const height = canvas.height - PADDING * 2;

      const convertLength = (length: number): number => {
        return Math.ceil(length * (width / fieldW));
      };

      const convertCoords = (coords: XY | XYZ): XY => {
        const [x, y] = coords;

        return [
          (x + fieldW / 2) * (width / fieldW) + PADDING,
          (-y + fieldH / 2) * (height / fieldH) + PADDING,
        ];
      };

      ctx.fillStyle = "#00aa00";
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      worldState.field_geom?.line_segments?.forEach?.(({ p1, p2 }) => {
        const [x1, y1] = convertCoords(p1);
        const [x2, y2] = convertCoords(p2);
        ctx.strokeStyle = "white";
        ctx.beginPath();
        ctx.moveTo(x1, y1);
        ctx.lineTo(x2, y2);
        ctx.stroke();
      });

      const drawPlayer = (
        serverPos: XY,
        orientation: number,
        color: string,
        selected: boolean
      ) => {
        const [x, y] = convertCoords(serverPos);
        const robotCanvasRadius = convertLength(ROBOT_RADIUS);
        ctx.fillStyle = color;
        ctx.beginPath();
        ctx.arc(x, y, robotCanvasRadius, 0, 2 * Math.PI);
        ctx.fill();

        const angle = -orientation;
        ctx.save();
        ctx.translate(x, y);
        ctx.rotate(angle);
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.lineTo(robotCanvasRadius, 0);
        ctx.closePath();
        ctx.restore();
        ctx.stroke();

        if (selected) {
          ctx.strokeStyle = "white";
          ctx.lineWidth = 2;
          ctx.beginPath();
          ctx.arc(x, y, robotCanvasRadius + 2, 0, 2 * Math.PI);
          ctx.stroke();
        }
      };
      own_players.forEach(({ id, raw_position, orientation }) =>
        drawPlayer(raw_position, orientation, "blue", id === selectedPlayerId)
      );
      opp_players.forEach(({ raw_position, orientation }) =>
        drawPlayer(raw_position, orientation, "yellow", false)
      );

      if (ball) {
        const ballPos = convertCoords(ball.position);
        const ballCanvasRadius = convertLength(BALL_RADIUS);
        ctx.fillStyle = "red";
        ctx.beginPath();
        ctx.arc(ballPos[0], ballPos[1], ballCanvasRadius, 0, 2 * Math.PI);
        ctx.fill();
      }

      if (worldState.own_players.length > 0) {
        let selectedPlayer = worldState.own_players[0];
        if (selectedPlayerId === null) {
          setSelectedPlayerId(worldState.own_players[0].id);
        } else {
          const _selectedPlayer = worldState.own_players.find(
            (player) => player.id === selectedPlayerId
          );
          if (_selectedPlayer) {
            selectedPlayer = _selectedPlayer;
          } else {
            setSelectedPlayerId(selectedPlayer.id);
          }
        }
      }

      drawCross(ctx, crossX, crossY);

      frame = requestAnimationFrame(render);
    };

    render();

    return () => {
      if (frame !== null) {
        cancelAnimationFrame(frame);
      }
    };
  }, [selectedPlayerId, crossX, crossY]);

  function handleXChange(e: React.ChangeEvent<HTMLInputElement>): void {
    const newX = parseInt(e.target.value);
    setCrossX(newX);
  }

  function handleYChange(e: React.ChangeEvent<HTMLInputElement>): void {
    const newY = parseInt(e.target.value);
    setCrossY(newY);
  }

  function drawCross(ctx: CanvasRenderingContext2D, x: number, y: number) {
    const canvas = canvasRef.current;
    const width = canvas!.width - PADDING * 2;
    const height = canvas!.height - PADDING * 2;
    const fieldH = worldStateRef.current?.field_geom?.field_width ?? 0;
    const fieldW = worldStateRef.current?.field_geom?.field_length ?? 0;
    const crossCanvasX = ((crossX + fieldW / 2) / fieldW) * width + PADDING;
    const crossCanvasY = ((-crossY + fieldH / 2) / fieldH) * height + PADDING;

    const crossSize = 10; // Length of each arm of the cross
    ctx.strokeStyle = "red";
    ctx.beginPath();
    ctx.moveTo(crossCanvasX - crossSize, crossCanvasY); // Horizontal line
    ctx.lineTo(crossCanvasX + crossSize, crossCanvasY);
    ctx.moveTo(crossCanvasX, crossCanvasY - crossSize); // Vertical line
    ctx.lineTo(crossCanvasX, crossCanvasY + crossSize);
    ctx.stroke();
  }

  return (
    <main className="cont">
      <div className="sidebar" style={{ color: "white" }}>
        <h3>Controls</h3>
        <ul>
          <li>
            Use <strong>W,A,S,D</strong> to move the robot
          </li>
          <li>
            Use <strong>Q,E</strong> to rotate the robot
          </li>
          <li>
            Hold <strong>Space</strong> to use the dribbler
          </li>
          <li>
            Press <strong>V</strong> to kick (not implemented yet, should also
            allow charging the kick + showing this)
          </li>
        </ul>
        <label>
          X-Axis:
          <input
            type="range"
            min={-fieldH / 2}
            max={fieldH / 2}
            value={crossX}
            onChange={handleXChange}
          />
          {crossX}
        </label>
        <br />
        <label>
          Y-Axis:
          <input
            type="range"
            min={-fieldW / 2}
            max={fieldW / 2}
            value={crossY}
            onChange={handleYChange}
          />
          {crossY}
        </label>
      </div>

      <div className="sidebar"></div>

      <canvas ref={canvasRef} width={840} height={600} className="canvas" />

      <div className="sidebar"></div>
    </main>
  );
};

export default App;

function createCmd(id: number, pressedKeys: Set<String>): PlayerCmd {
  const cmd: PlayerCmd = {
    id,
    sx: 0,
    sy: 0,
    w: 0,
    dribble_speed: 0,
    arm: false,
    disarm: false,
    kick: false,
  };

  if (pressedKeys.has("w")) {
    cmd.sx = 2;
  }
  if (pressedKeys.has("s")) {
    cmd.sx = -2;
  }
  if (pressedKeys.has("a")) {
    cmd.sy = -2;
  }
  if (pressedKeys.has("d")) {
    cmd.sy = 2;
  }
  if (pressedKeys.has("q")) {
    cmd.w = 3;
  }
  if (pressedKeys.has("e")) {
    cmd.w = -3;
  }
  if (pressedKeys.has(" ")) {
    cmd.dribble_speed = 200;
  }
  if (pressedKeys.has("v")) {
    cmd.kick = true;
  } else {
    cmd.kick = false;
  }

  return cmd;
}
