// webui/src/components/Field.vue
<script setup lang="ts">
// ---------------- IMPORTS ----------------
// core
import { ref, onMounted } from "vue";

// store
import { storeToRefs } from "pinia";
import { useAppStore } from "../store/app";

// types
import type { World, XY, XYZ, RenderData } from "../types";

// components
import Bot from "./Bot.vue";

// ---------------- CODE ----------------
// Store setup
const appStore = useAppStore();
const { PADDING, ROBOT_RADIUS, BALL_RADIUS } = storeToRefs(appStore);

// Canvas variables
const canvas = ref<HTMLCanvasElement | null>(null);
let canvasWidth = ref<number>(0);
let canvasHeight = ref<number>(0);

let state: World | null = null;

/**
 * Fits the canvas to its full width/height
 * @param canvas - the canvas where our filed is rendered
 */
function fitToContainer(canvas: HTMLCanvasElement) {
  canvas.width = canvas.offsetWidth;
  canvas.height = canvas.offsetHeight;
}

/**
 * Renders the field
 */
function render(ctx: CanvasRenderingContext2D) {
  if (canvas.value && state) {
    // Adjusting the canvas to the right dimenstions
    fitToContainer(canvas.value);

    canvasWidth.value = canvas.value.width;
    canvasHeight.value = canvas.value.height;

    // Add some padding to the canvas
    const width = canvasWidth.value - PADDING.value * 2;
    const height = canvasHeight.value - PADDING.value * 2;

    const { own_players, opp_players, ball } = state;
    const fieldH = state.field_geom.field_width;
    const fieldW = state.field_geom.field_length;

    console.log(canvasWidth.value, canvasHeight.value);

    // ---------------- FILL FIELD WITH COLOR ----------------
    ctx.fillStyle = "#3bad59";
    ctx.clearRect(0, 0, canvasWidth.value, canvasHeight.value);
    ctx.fillRect(0, 0, canvasWidth.value, canvasHeight.value);

    // ---------------- DRAW LINES ----------------
    state.field_geom.line_segments.forEach(({ p1, p2 }: { p1: XY; p2: XY }) => {
      const [x1, y1]: [number, number] = convertCoords(
        p1,
        width,
        fieldW,
        height,
        fieldH
      );
      const [x2, y2]: [number, number] = convertCoords(
        p2,
        width,
        fieldW,
        height,
        fieldH
      );
      ctx.strokeStyle = "white";
      ctx.beginPath();
      ctx.moveTo(x1, y1);
      ctx.lineTo(x2, y2);
      ctx.stroke();
    });

    // ---------------- DRAW BALL ----------------
    const ballPos = convertCoords(ball.position, width, fieldW, height, fieldH);
    const ballCanvasRadius = convertLength(BALL_RADIUS.value, width, fieldW);
    ctx.fillStyle = "red";
    ctx.beginPath();
    ctx.arc(ballPos[0], ballPos[1], ballCanvasRadius, 0, 2 * Math.PI);
    ctx.fill();

    // ---------------- DRAW PLAYERS ----------------
    const drawPlayer = (serverPos: XY, color: string) => {
      const [x, y]: [number, number] = convertCoords(
        serverPos,
        width,
        fieldW,
        height,
        fieldH
      );

      const robotCanvasRadius = convertLength(
        ROBOT_RADIUS.value,
        width,
        fieldW
      );
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.arc(x, y, robotCanvasRadius, 0, 2 * Math.PI);
      ctx.fill();
    };

    own_players.forEach(({ position }: { position: XY }) =>
      drawPlayer(position, "blue")
    );
    opp_players.forEach(({ position }: { position: XY }) =>
      drawPlayer(position, "yellow")
    );
  } else {
    console.log("state is not working");
  }
}

/**
 * Convert from server length to canvas length.
 */
const convertLength = (
  length: number,
  width: number,
  fieldW: number
): number => {
  return Math.ceil(length * (width / fieldW));
};

/**
 * Convert from server coordinates to canvas coordinates.
 *
 * The server's coordinate system has its origin at the center of the field,
 */
const convertCoords = (
  coords: XY | XYZ,
  width: number,
  fieldW: number,
  height: number,
  fieldH: number
): XY => {
  const [x, y] = coords;

  return [
    (x + fieldW / 2) * (width / fieldW) + PADDING.value,
    (-y + fieldH / 2) * (height / fieldH) + PADDING.value,
  ];
};

// ---------------- Lifecycle hooks ----------------
onMounted(async () => {
  const context = ref(canvas.value?.getContext("2d"));
  if (context.value) {
    // Retrieve state (from the mock server)
    const res = await fetch("/api/state");
    state = await res.json();
    render(context.value);
  }

  // const interval = setInterval(async () => {
  //   // Getting the context of the canvas
  //   const context = ref(canvas.value?.getContext("2d"));
  //   if (context.value) {
  //     // Retrieve state (from the mock server)
  //     const res = await fetch("/api/state");
  //     state = await res.json();
  //     render(context.value);
  //   }
  // }, 100);
});
</script>

<template>
  <canvas ref="canvas" class="football-field">
  </canvas>
</template>

<style scoped>
.football-field {
  width: 100%;
  aspect-ratio: 5/2;
}
</style>

// webui/src/views/Field.tsx
import React, { FC, useEffect, useRef } from "react";
import { WorldStatus, useWorldState } from "../api";
import { Vector2, Vector3, WorldData } from "../bindings";
import { useResizeObserver } from "@/lib/useResizeObserver";

const ROBOT_RADIUS = 0.14 * 1000;
const BALL_RADIUS = 0.043 * 1000;
const DEFAULT_FIELD_SIZE = [10400, 7400];
const CANVAS_PADDING = 20;
const CONT_PADDING_PX = 8;

const FIELD_GREEN = "#15803d";

const Field: FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const world = useWorldState();
  const worldData = world.status === "connected" ? world.data : null;
  const contRef = useRef(null);

  const { width: contWidth = 0, height: contHeight = 0 } = useResizeObserver({
    ref: contRef,
  });
  const fieldSize = [
    (worldData?.field_geom?.field_length ?? DEFAULT_FIELD_SIZE[0]) +
      2 * CANVAS_PADDING,
    (worldData?.field_geom?.field_width ?? DEFAULT_FIELD_SIZE[1]) +
      2 * CANVAS_PADDING,
  ];
  const availableHeight = contHeight - 2 * CONT_PADDING_PX;
  const availableWidth = contWidth - 2 * CONT_PADDING_PX;
  const canvasWidth = Math.min(
    availableWidth,
    availableHeight * (fieldSize[0] / fieldSize[1])
  );
  const canvasHeight = canvasWidth * (fieldSize[1] / fieldSize[0]);

  // Render the field when the world state changes
  useEffect(() => {
    if (!canvasRef.current) return;

    clearCanvas(canvasRef.current);
    if (worldData) {
      render(canvasRef.current, worldData, null);
    }
  }, [worldData, canvasWidth]);

  return (
    <div
      ref={contRef}
      className="w-full h-full flex items-center justify-center overflow-hidden"
      style={{ padding: CONT_PADDING_PX }}
    >
      <canvas
        ref={canvasRef}
        className="border-8 border-green-950 rounded"
        width={canvasWidth}
        height={canvasHeight}
      />
    </div>
  );
};

const clearCanvas = (canvas: HTMLCanvasElement) => {
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = FIELD_GREEN;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillRect(0, 0, canvas.width, canvas.height);
};

/**
 * Render the field on the canvas
 */
const render = (
  canvas: HTMLCanvasElement,
  worldState: WorldData,
  selectedPlayerId: number | null
) => {
  const ctx = canvas.getContext("2d")!;

  const { own_players, opp_players, ball } = worldState;
  const fieldW = worldState.field_geom?.field_length ?? 0;
  const fieldH = worldState.field_geom?.field_width ?? 0;
  const screenFieldW = canvas.width - CANVAS_PADDING * 2;
  const screenFieldH = canvas.height - CANVAS_PADDING * 2;

  const convertCoords = (coords: Vector2 | Vector3): Vector2 => {
    const [x, y] = coords;

    return [
      (x + fieldW / 2) * (screenFieldW / fieldW) + CANVAS_PADDING,
      (-y + fieldH / 2) * (screenFieldH / fieldH) + CANVAS_PADDING,
    ];
  };

  const convertLength = (length: number): number => {
    return Math.ceil(length * (screenFieldW / fieldW));
  };

  const drawPlayer = (
    serverPos: Vector2,
    yaw: number,
    color: string,
    selected: boolean
  ) => {
    const [x, y] = convertCoords(serverPos);
    const robotCanvasRadius = convertLength(ROBOT_RADIUS);
    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.arc(x, y, robotCanvasRadius, 0, 2 * Math.PI);
    ctx.fill();

    const angle = -yaw;
    ctx.save();
    ctx.translate(x, y);
    ctx.rotate(angle);
    ctx.beginPath();
    ctx.moveTo(0, 0);
    ctx.lineTo(robotCanvasRadius, 0);
    ctx.closePath();
    ctx.restore();
    ctx.stroke();

    if (selected) {
      ctx.strokeStyle = "white";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.arc(x, y, robotCanvasRadius + 2, 0, 2 * Math.PI);
      ctx.stroke();
    }
  };

  // Draw the field lines
  worldState.field_geom?.line_segments?.forEach?.(({ p1, p2 }) => {
    const [x1, y1] = convertCoords(p1);
    const [x2, y2] = convertCoords(p2);
    ctx.strokeStyle = "white";
    ctx.beginPath();
    ctx.moveTo(x1, y1);
    ctx.lineTo(x2, y2);
    ctx.stroke();
  });

  // Draw the player robots
  own_players.forEach(({ id, raw_position, yaw }) =>
    drawPlayer(raw_position, yaw, "blue", id === selectedPlayerId)
  );
  opp_players.forEach(({ raw_position, yaw }) =>
    drawPlayer(raw_position, yaw, "yellow", false)
  );

  // Draw the ball
  if (ball) {
    const ballPos = convertCoords(ball.position);
    const ballCanvasRadius = convertLength(BALL_RADIUS);
    ctx.fillStyle = "red";
    ctx.beginPath();
    ctx.arc(ballPos[0], ballPos[1], ballCanvasRadius, 0, 2 * Math.PI);
    ctx.fill();
  }
};

export default Field;
